/* AUTH TYPES */

export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const USER_INFO = 'USER_INFO';

/* PROFILE TYPES */

export const FETCH_USER = 'FETCH_USER';
export const CHANGE_INFO = 'CHANGE_INFO';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const ADD_TAG = 'ADD_TAG';
export const DELETE_TAG = 'DELETE_TAG';
export const MANAGE_BIO = 'MANAGE_BIO';
export const UPLOAD_PICTURE = 'UPLOAD_PICTURE';
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE';
export const DELETE_PICTURE = 'DELETE_PICTURE';

/* CHAT TYPES */

export const HAS_MATCHED = 'HAS_MATCHED';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';

/* MATCH TYPES */

export const MATCH_SUGGESTION = 'MATCH_SUGGESTION';
export const RESEARCH_USERS = 'RESEARCH_USERS';
export const FETCH_TAGS = 'FETCH_TAGS';